
[general]
	#Blinking start time before the item despawns, in seconds
	#Range: 0 ~ 36000
	flashStartTime = 20
	#Time until items will despawn (Change only if the items in the pack have different time limit)
	#Range: 0 ~ 36000
	despawnTime = 6000
	#Set to true to have item flash faster as it gets closer to despawning
	urgentFlash = true

