
["Dynamic Trees + Tectonic Compat Mod Config"]
	#If "true", implements fixes for failed tree cancellation in tectonic biomes. 
	#Replaces tree features in biomes that tree cancellation has failed. 
	#Defaults to "true".
	tectonic_tree_features_fix_entry = true
	#If "true", implements fix for sandy tectonic biomes when used with terratonic. 
	#Implements changes above, but also adds force_sand feature from terratonic. 
	#Defaults to "false".
	terratonic_sand_fix_entry = false

