
[types]

	[types.wood_type]

		[types.wood_type.quark]
			bamboo = true
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

	[types.leaves_type]

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.dynamictrees]
			spruce = true
			oak_undergrowth = true
			oak = true
			mangrove = true
			jungle_undergrowth = true
			jungle = true
			flowering_azalea = true
			dark_oak = true
			birch = true
			azalea = true
			acacia = true

		[types.leaves_type.dtquark]
			serene_blossom = true
			sunny_blossom = true
			fiery_blossom = true
			sweet_blossom = true
			frosty_blossom = true
			warm_blossom = true

[entries]

	[entries.wood_type]

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			chest = true
			stripped_post = true
			ladder = true
			trapped_chest = true
			bookshelf = true
			hollow_log = true

		[entries.wood_type.mcwdoors]
			beach_door = true
			nether_door = true
			stable_head_door = true
			barn_door = true
			mystic_door = true
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			cottage_door = true
			four_panel_door = true
			japanese_door = true
			western_door = true
			bark_glass_door = true
			paper_door = true
			classic_door = true
			bamboo_door = true
			swamp_door = true
			glass_door = true
			stable_door = true
			modern_door = true
			waffle_door = true

		[entries.wood_type.mcwfences]
			horse_fence = true
			highley_gate = true
			pyramid_gate = true
			stockade_fence = true
			wired_fence = true
			picket_fence = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.mcwfences]
			hedge = true

